"""Resume_reasoning_similarity_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_XM-j3WXfOKPs2vWb81A63r55g9-Nhk
"""

!pip install scikit-learn

!pip install sentence-transformers

!pip install python-docx

!pip install pypdf2  # install pypdf2 for working with PDF files

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from docx import Document
import PyPDF2
from docx.opc.exceptions import PackageNotFoundError

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

!pip install python-docx  # Assuming python-docx is the correct package name
# After successful installation, restart your kernel
# If you're in Google Colab, use the following to install to the correct kernel:
get_ipython().system('python -m pip install --upgrade python-docx')

import zipfile
from docx import Document

def read_file(file_path):
    """
    Extracts text from a file based on its format (PDF or DOCX).

    Args:
        file_path (str): Path to the file.

    Returns:
        str: Extracted text from the file.
    """
    if file_path.lower().endswith('.pdf'):
        # If PDF, extract text
        with open(file_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            text = "".join(page.extract_text() for page in reader.pages if page.extract_text())
        return text
    elif file_path.lower().endswith('.docx'):
        try:
            # Try to open the DOCX file
            doc = Document(file_path)
            text = "\n".join(paragraph.text for paragraph in doc.paragraphs)
            return text
        except zipfile.BadZipFile:
            # Handle invalid or corrupted DOCX file
            raise ValueError("The provided .docx file seems to be corrupted or invalid.")
    else:
        raise ValueError("Unsupported file format. Only 'pdf' and 'docx' are supported.")

def calculate_similarity(jd_embedding, resume_embedding):
    """
    Calculate cosine similarity between job description and resume text embeddings.
    """
    similarity_score = cosine_similarity(jd_embedding, resume_embedding)[0][0] * 100  # Get percentage score

    # Print similarity reasoning
    print("\nSimilarity Score:", f"{similarity_score:.2f}%")
    print("\nReasoning:")

    if similarity_score > 60:
        print("The high similarity indicates a strong alignment between the job description and the resume.")
    elif similarity_score > 30:
        print("The moderate similarity suggests some overlap between the resume and the job description.")
    else:
        print("The low similarity indicates a weak alignment between the resume and the job description.")

    return similarity_score

def main(jd_file_path, resume_file_path):
    try:
        # Step 1: Extract text from the files (resume and job description)
        jd_text = read_file("/content/JOB DESCRIPTION.docx")  # Path to job description file
        resume_text = read_file("/content/PavanK_Resume.docx")  # Path to resume file
        # Step 2: Get embeddings for JD and resume using pre-trained model
        jd_embedding = model.encode([jd_text])  # Get embedding for job description
        resume_embedding = model.encode([resume_text])  # Get embedding for resume

        # Step 3: Calculate the similarity score and provide reasoning
        similarity_score = calculate_similarity(jd_embedding, resume_embedding)

        return similarity_score  # Return the similarity score

    except Exception as e:
        print(f"Error: {e}")
        return None

!pip install python-docx # Make sure you are using python-docx package.
# Restart the kernel after installation.

# If using Google Colab, install for the correct kernel:
get_ipython().system('python -m pip install --upgrade python-docx')
# Restart the kernel again after running the above cell.

import zipfile
from docx import Document
# ... rest of your code

def read_file(file_path):
    """
    Extracts text from a file based on its format (PDF or DOCX).

    Args:
        file_path (str): Path to the file.

    Returns:
        str: Extracted text from the file.
    """
    if file_path.lower().endswith('.pdf'):
        # If PDF, extract text
        with open(file_path, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            text = "".join(page.extract_text() for page in reader.pages if page.extract_text())
        return text
    elif file_path.lower().endswith('.docx'):
        try:
            # Try to open the DOCX file
            doc = Document(file_path)
            text = "\n".join(paragraph.text for paragraph in doc.paragraphs)
            return text
        except zipfile.BadZipFile:
            # Handle invalid or corrupted DOCX file
            raise ValueError("The provided .docx file seems to be corrupted or invalid.")
    else:
        raise ValueError("Unsupported file format. Only 'pdf' and 'docx' are supported.")

def calculate_similarity(jd_embedding, resume_embedding):
    """
    Calculate cosine similarity between job description and resume text embeddings.
    """
    similarity_score = cosine_similarity(jd_embedding, resume_embedding)[0][0] * 100  # Get percentage score

    # Print similarity reasoning
    print("\nSimilarity Score:", f"{similarity_score:.2f}%")
    print("\nReasoning:")

    # Reasoning based on similarity score
    if similarity_score > 60:
        print("The high similarity indicates a strong alignment between the job description and the resume.")
        print("This means the resume contains skills, experiences, and qualifications that match well with the job.")
    elif similarity_score > 30:
        print("The moderate similarity suggests some overlap between the resume and the job description.")
        print("There are some relevant skills or experiences in the resume, but it might not be a perfect match for the job requirements.")
    else:
        print("The low similarity indicates a weak alignment between the resume and the job description.")
        print("The resume likely lacks key qualifications or experience that are important for the job.")

    return similarity_score

!pip install PyPDF2

import PyPDF2

if __name__ == "__main__":
    jd_file = "/content/JOB DESCRIPTION.docx"  # Replace with actual file path
    resume_file = "/content/PavanK_Resume.docx"  # Replace with actual file path

    # Call the main function to get the similarity score
    similarity_score = main(jd_file, resume_file)
