services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      CORS_ALLOWED_ORIGINS: "https://resume-builder-5mbc.onrender.com"
